openapi: 3.0.1
info:
  title: Menu API
  version: 1.0.0
paths:
  /signup:
    post:
      tags:
        - user
      summary: Signup
      operationId: signup
      requestBody:
        description: Signup Object that needs to be added to the User
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
        400:
          description: failed operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
  /login:
    post:
      tags:
        - user
      summary: Signin
      operationId: login
      requestBody:
        description: Signin
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
        400:
          description: failed operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
components:
  schemas:
    CommonResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    SignupRequest:
      type: object
      properties:
        username:
          type: string
        displayName:
          type: string
        password:
          type: string
        email:
          type: string
      required:
        - username
        - password
        - email
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
