spring:
  datasource:
    url: jdbc:postgresql//@localhost:5432/menu
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        dialect: org.hibernate.dialect.PostgreSQLDialect
