spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/menu?useSSL=false
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/menu}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        dialect: org.hibernate.dialect.PostgreSQLDialect
