spring:
  application:
    name: menu-api
  profiles:
    include:
      - jpa
  jackson:
    default-property-inclusion: non_null
server:
  shutdown: graceful
logging:
  level:
    default: INFO
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com:
      yang:
        menu:
          menuapi: DEBUG

jwtauth:
  no-auth-url-patterns:
    - /signup
    - /login
  secret: hogehoge
  expire-ms: 1800000
  issuer: y2hyun